### PR TITLE
Combine test and release workflows & Add Winget Releaser

### PR DESCRIPTION
**Pull request by sitiom**
This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

I have created a PR to add [PowerSession](https://github.com/microsoft/winget-pkgs/pull/77905) to Winget, and this workflow will be used to update it.

Before merging this:
1. Add a PAT with `public_repo` scope as a repository secret named `WINGET_TOKEN` (or rename the secret name in the workflow).

example

2. Fork https://github.com/microsoft/winget-pkgs under @Watfaq. The action will use that fork for making a branch and creating a PR with the upstream [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository on every release.
3. Make sure the PAT owner has signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs) for winget-pkgs.

If you would like to read about this action further, the documentation is [here](https://bittu.eu.org/docs/wr-intro), and the source code is [here](https://github.com/vedantmgoyal2009/winget-releaser).

If you want to see an example of a PR created using this action, see [microsoft/winget-pkgs/pulls (Pull request has been automatically created using 🛫 WinGet Releaser)](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+sort%3Aupdated-desc+Pull+request+has+been+automatically+created+using+%F0%9F%9B%AB+WinGet+Releaser).

Other changes:
- Combine `ci.yml` and `release.yml` into one workflow.
- Add binary artifacts
- Limit to 5 keywords in `Cargo.toml`. Fixes https://github.com/Watfaq/PowerSession-rs/issues/44#issuecomment-1236064415

### CODE REVIEW

**Review by ibigbug — APPROVED** [review]
Thank you!

**Comment by sitiom** [comment]
@ibigbug Great, please try republishing now

**Comment by ibigbug** [comment]
@sitiom https://github.com/Watfaq/PowerSession-rs/actions/runs/3027797502

**Comment by ibigbug** [comment]
@sitiom looks like it worked https://github.com/microsoft/winget-pkgs/compare/master...Watfaq:winget-pkgs:Watfaq.PowerSession-0.1.7-8284D0C5832904?expand=1

**Comment by sitiom** [comment]
Nice!

**Comment by sitiom** [comment]
@ibigbug I forgot an extra step: You should keep the fork regularly updated with [Pull](https://github.com/apps/pull). Otherwise, it will eventually try to update the old workflows without the `workflow` scope, resulting in an error.

**Pull request merged**
